### ISSUE TITLE
VM Update Failed 

### ISSUE THREAD

**Issue by anandshelot** [ArasLabs/vm-sample-application#1]
While installing VM package we are getting below issue. Early response is appreciated. 
![vm-issue](https://user-images.githubusercontent.com/36917838/36781180-28d18160-1c9b-11e8-8966-3096b9858cef.PNG)

**Comment by EliJDonahue** [comment]
Hi anandshelot,

When selecting the install path for your Innovator instance, be sure to select the Innovator subfolder. 

Ex: If your Innovator instance is installed in `C:\Program Files (x86)\Aras\11SP12`, select `C:\Program Files (x86)\Aras\11SP12\Innovator`.

I will update the readme to clarify this step in the installation.

Eli

**Comment by EliJDonahue** [comment]
Installation steps are updated to clarify which folder to select:

![2018-02-28_10-32-49](https://user-images.githubusercontent.com/6794866/36796152-e519902a-1c72-11e8-98f8-cebb4ff86cae.png)

**Comment by anandshelot** [comment]
Hello EliJDonahue,

Thank you for your quick response. It works for me!!!
