### ISSUE TITLE
Generic Item Structure & Family Structure Tabs missing from Generic Item Relationship Types (Instance: Innovator 11SP12)

### ISSUE THREAD

**Issue by sachinbijadi** [ArasLabs/vm-sample-application#2]
![cs_sample_configurator services](https://user-images.githubusercontent.com/42272230/43958397-9031cf82-9cab-11e8-9c72-13256c6b9961.png)
Issue with the generic item (Above image shows the item as it appears on our Innovator 11SP12 instance).
While the configurator Services Guidebook shows that along with the Generic Structure tab, ther is a Gneric Item structure tab (like so:
![image](https://user-images.githubusercontent.com/42272230/43958545-1492bd5e-9cac-11e8-89bb-c744ef65f131.png)
and there should be a Family Structure tab (like so:
![image](https://user-images.githubusercontent.com/42272230/43958570-267dad30-9cac-11e8-991a-0f272901d413.png)
However these 2 tabs do not appear when the configurator services is installed for some reason. These are the relationship types that are linked to Generic item ItemType in Innovator:
![image](https://user-images.githubusercontent.com/42272230/43958681-87995b32-9cac-11e8-881a-9e668c03cd4b.png)
(I have added an additional Products usage relationship to link products to the generic item at the highest level). 

What is the reason for those 2 tabs to not appear? They are really useful visual representation of the configuration structure, so I am really handicapped without them. Can anybody suggest a fix or update the package to make corrections? Thanks!

**Comment by sachinbijadi** [comment]
Any updates on this? Similarly the Order itemtype is missing as well (as shown in the DEMO video for Variant management)

**Comment by cgillis-aras** [comment]
The Relationship Tabs that you're seeing in the documentation were introduced as additional enhancements in the SP14 version of the VM Sample Appllication. The link in the README of the project page points to the latest version of the documentation, so I would recommend looking at the pdfs in the /Documentation/ folder of your downloaded SP12 sample app for the relevant diagrams to that version of the environment.

To answer your second question, the Order ItemType that was shown off in the demo video is not intended to be a part of the sample application. It was intended as an example in the demo video to better help people understand Variant Management by showing how it could be used to confirm that an order from a customer could actually be built.

**Comment by sachinbijadi** [comment]
Thanks for the headsup. Indeed I was looking at the wrong documentation.

Is it possible at all in any way to build that capability (Generic Item structure and Family structure) in the application in Sp12 environemtnas well?

**Comment by sachinbijadi** [comment]
As far as the Order Itemtype goes, is it possible to create that Itemtype to match the capabilities shown in the demo, from scratch? Any resources to guide me on doing that?
P.S>  I am not a programmer, just an product design engineer who is trying to adapt this tool to a really complication product that we are building.

**Comment by sachinbijadi** [comment]
@cgillis-aras , Is it possible to add a new relationship type with the family structure view for the sample application in Innovator 11sp12?  I assume this is quite similar to the BOM structure view? Would it be possible to guide me on how to set this up, as this is a really useful feature to see the whole configured superbom structure, instead of having to click through each level of the hierarchy
